### ISSUE TITLE
Deactivate spell-checking/auto-correction

### ISSUE THREAD

**Issue by tsdh** [alexander-yakushev/foreclojure-android#1]
I don't know if that's possible, but it would be great if in the text field where you write your solution the automatic spell-checking and auto-correction were disabled.  Currently, when I type `(fn<SPACE>` I end up with `(fun ` [1].  Of course, I could add `fn` to my personal dictionary but I'd much prefer not to because that's not really a word in normal speech.

[1] Of course I like to have fun but certainly not in this case. ;-)

**Comment by alexander-yakushev** [comment]
Yes, this is in fact very easy to do, I just overlooked this bug. I will publish the fix soon, with some other minor improvements.

**Comment by tsdh** [comment]
Awesome, thanks!

**Comment by alexander-yakushev** [comment]
I just pushed the new version to Google Play, which besides this fix contains other improvements to the codebox. The update should be available in a few hours.

**Comment by tsdh** [comment]
Yes, works fine now.  And the other new features are great, too.  The only bad thing now is that (), and especially [] and {} are so badly accessible on a stock android 5 keyboard but I guess there's nothing you can do about it.

**Comment by alexander-yakushev** [comment]
I think I can't, AFAIK only user can control which software keyboard pops out in the edittext widgets.

A solution could be for you to install something like this: https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en

**Comment by tsdh** [comment]
Yes, that one is handy for 4clojure (or coding in general).  What would be great is a way to always use this keyboard for 4clojure without having to change it back and forth globally.
