### ISSUE TITLE
Problem 47 impossible to solve

### ISSUE THREAD

**Issue by itsananderson** [alexander-yakushev/foreclojure-android#2]
Love the app, by the way!

Got stuck on problem 47. I'm pretty sure the answer should be `4`, but the last unit test throws the following error no matter what input it gets:

```
(not (contains? '(1 2 4) __))
=> java.util.confurrent.ExecutionException:
   java.lang.IllegalArgumentException:
   contains? not supported on type clojure.lang.PersistentList
```

I tried inputting `4` as an answer on the website, and it was accepted, so looks like this is a difference between the app and the website's code evaluation.

The website seems to not care about the type of the input given to `contains?`, but in the app it throws exceptions when given a `PersistentList`. I'm new to Clojure, so I'm not sure if this is a difference between Clojure versions or something else.

**Comment by alexander-yakushev** [comment]
Yes, there is a problem with this... problem: 4clojure/4clojure#266. Still waiting for their response. Still, thanks for reporting!

**Comment by itsananderson** [comment]
Aha. Didn't think to check the 4clojure project :)

Looks like the problems are initialized from here: https://github.com/4clojure/4clojure/blob/develop/src/foreclojure/data_set.clj, but then they're loaded into MongoDB, so presumably they'll also need to update a database entry on the live server.

**Comment by alexander-yakushev** [comment]
Given the last commit as in Man 2013, I'm not expecting them to fix this any time soon (if ever). Perhaps I should just remove/rewrite the offending test keeping answer the same.

**Comment by alexander-yakushev** [comment]
Eventually I just removed the offending test from the problem. It doesn't change the solution, and fixes the failure.

**Comment by peter-lyons-kehl** [comment]
Hi Will,

Thank you for reporting. This has also been fixed on 4clojure.com - thanks to you.
