### ISSUE TITLE
Broken on KitKat

### ISSUE THREAD

**Issue by johnmn3** [alexander-yakushev/foreclojure-android#3]
Mostly broken on KitKat. There's a lot of NoClassDefFound for android/os/PersistableBundle, which isn't available on KitKat. Not sure if that is the root cause.

**Comment by alexander-yakushev** [comment]
I know what causes this, but I certainly fixed it in the latest Clojure version which 4Clojure 0.2.0 is built with. I tried running the app on 4.4 emulator and 4.4 device, and it worked fine (before the fix it failed with those NoClassDefFound exceptions). So I need more details about your device, which version you launch etc.

**Comment by johnmn3** [comment]
Did you use [org.clojure-android/clojure "1.7.0-r2"]?

I tried it on a 4.4 device and a 4.4 emulator. Ran "lein droid doall" from a fresh git clone.

**Comment by johnmn3** [comment]
And I'm on Windows 10. Leiningen 2.5.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM. I'm running the Android SDK folder from the Android Studio IDE distribution.

**Comment by alexander-yakushev** [comment]
Yes, I used r3. So is the version from the Play Market broken for you, or only the one you build yourself?

**Comment by johnmn3** [comment]
The version from the play market works great! :)

**Comment by alexander-yakushev** [comment]
Oh, I see what you mean. Because of the `gen-class` quirks, in debug version you can't really target a newer SDK (21, in this case) and run it on an older device. So if you want to develop for the later SDK you need a newer device, or emulator.

When you build a release version, it will work on all devices down to 4.0.

**Comment by johnmn3** [comment]
Yup, that worked. Thanks!

**Comment by alexander-yakushev** [comment]
You are welcome, thanks for reminding me about this.
